import {isLocale, type Locale} from "@/lib/locales";

export const billingActionCopy: Record<Locale, {manage: string; busy: string; checkoutError: string; portalError: string; loginRequired: string; addonUnavailable: string; noPortalCustomer: string}> = {
  ar: {manage: "إدارة الاشتراك", busy: "جار المعالجة...", checkoutError: "تعذر إنشاء جلسة الدفع. يرجى المحاولة لاحقًا أو التواصل مع الدعم.", portalError: "تعذر فتح بوابة الفوترة. يرجى المحاولة لاحقًا أو التواصل مع الدعم.", loginRequired: "يرجى تسجيل الدخول قبل ترقية الخطة.", addonUnavailable: "حزم الدقائق الإضافية متاحة فقط للحسابات ذات الاشتراك النشط.", noPortalCustomer: "لا توجد سجلات فوترة قابلة للإدارة لهذا الحساب."},
  de: {manage: "Abo verwalten", busy: "Verarbeitung...", checkoutError: "Die Zahlung ist vorübergehend nicht verfügbar. Bitte versuche es später erneut oder kontaktiere den Support.", portalError: "Die Abo-Verwaltung ist vorübergehend nicht verfügbar. Bitte versuche es später erneut oder kontaktiere den Support.", loginRequired: "Bitte melde dich an, bevor du dein Paket aktualisierst.", addonUnavailable: "Zusatzminuten sind nur für Konten mit aktivem kostenpflichtigem Abo verfügbar.", noPortalCustomer: "Für dieses Konto gibt es noch keine verwaltbaren Rechnungsdaten."},
  en: {manage: "Manage subscription", busy: "Processing...", checkoutError: "Payment is temporarily unavailable. Please try again later or contact support.", portalError: "Subscription management is temporarily unavailable. Please try again later or contact support.", loginRequired: "Please sign in before upgrading your plan.", addonUnavailable: "Add-on minute packs are only available for accounts with an active paid subscription.", noPortalCustomer: "This account does not have a manageable billing record yet."},
  es: {manage: "Gestionar suscripción", busy: "Procesando...", checkoutError: "El pago no está disponible temporalmente. Inténtalo más tarde o contacta con soporte.", portalError: "La gestión de la suscripción no está disponible temporalmente. Inténtalo más tarde o contacta con soporte.", loginRequired: "Inicia sesión antes de mejorar tu plan.", addonUnavailable: "Los paquetes de minutos adicionales solo están disponibles para cuentas con una suscripción de pago activa.", noPortalCustomer: "Esta cuenta aún no tiene un registro de facturación gestionable."},
  fr: {manage: "Gérer l'abonnement", busy: "Traitement...", checkoutError: "Le paiement est temporairement indisponible. Réessayez plus tard ou contactez l'assistance.", portalError: "La gestion de l'abonnement est temporairement indisponible. Réessayez plus tard ou contactez l'assistance.", loginRequired: "Veuillez vous connecter avant de mettre à niveau votre forfait.", addonUnavailable: "Les packs de minutes supplémentaires sont réservés aux comptes avec un abonnement payant actif.", noPortalCustomer: "Ce compte ne dispose pas encore d'un dossier de facturation gérable."},
  hu: {manage: "Előfizetés kezelése", busy: "Feldolgozás...", checkoutError: "A fizetés átmenetileg nem érhető el. Próbáld újra később, vagy fordulj az ügyfélszolgálathoz.", portalError: "Az előfizetéskezelés átmenetileg nem érhető el. Próbáld újra később, vagy fordulj az ügyfélszolgálathoz.", loginRequired: "A csomag frissítése előtt jelentkezz be.", addonUnavailable: "A kiegészítő percek csak aktív fizetős előfizetéssel rendelkező fiókokhoz érhetők el.", noPortalCustomer: "Ehhez a fiókhoz még nincs kezelhető számlázási rekord."},
  id: {manage: "Kelola langganan", busy: "Memproses...", checkoutError: "Pembayaran sementara tidak tersedia. Coba lagi nanti atau hubungi dukungan.", portalError: "Pengelolaan langganan sementara tidak tersedia. Coba lagi nanti atau hubungi dukungan.", loginRequired: "Silakan masuk sebelum meningkatkan paket.", addonUnavailable: "Paket menit tambahan hanya tersedia untuk akun dengan langganan berbayar aktif.", noPortalCustomer: "Akun ini belum memiliki catatan penagihan yang dapat dikelola."},
  it: {manage: "Gestisci abbonamento", busy: "Elaborazione...", checkoutError: "Il pagamento è temporaneamente non disponibile. Riprova più tardi o contatta l'assistenza.", portalError: "La gestione dell'abbonamento è temporaneamente non disponibile. Riprova più tardi o contatta l'assistenza.", loginRequired: "Accedi prima di aggiornare il piano.", addonUnavailable: "I pacchetti di minuti aggiuntivi sono disponibili solo per account con un abbonamento a pagamento attivo.", noPortalCustomer: "Questo account non ha ancora un record di fatturazione gestibile."},
  ja: {manage: "サブスクリプション管理", busy: "処理中...", checkoutError: "現在、決済を利用できません。しばらくしてから再試行するか、サポートにお問い合わせください。", portalError: "現在、サブスクリプション管理を利用できません。しばらくしてから再試行するか、サポートにお問い合わせください。", loginRequired: "プランをアップグレードする前にログインしてください。", addonUnavailable: "追加分パックは、有効な有料サブスクリプションのあるアカウントでのみ利用できます。", noPortalCustomer: "このアカウントには管理可能な請求情報がまだありません。"},
  ko: {manage: "구독 관리", busy: "처리 중...", checkoutError: "현재 결제를 사용할 수 없습니다. 나중에 다시 시도하거나 지원팀에 문의해 주세요.", portalError: "현재 구독 관리를 사용할 수 없습니다. 나중에 다시 시도하거나 지원팀에 문의해 주세요.", loginRequired: "플랜을 업그레이드하기 전에 로그인해 주세요.", addonUnavailable: "추가 시간 패키지는 활성 유료 구독 계정에서만 사용할 수 있습니다.", noPortalCustomer: "이 계정에는 아직 관리 가능한 결제 기록이 없습니다."},
  nl: {manage: "Abonnement beheren", busy: "Verwerken...", checkoutError: "Betalen is tijdelijk niet beschikbaar. Probeer het later opnieuw of neem contact op met support.", portalError: "Abonnementbeheer is tijdelijk niet beschikbaar. Probeer het later opnieuw of neem contact op met support.", loginRequired: "Log in voordat je je abonnement upgradet.", addonUnavailable: "Add-onminuten zijn alleen beschikbaar voor accounts met een actief betaald abonnement.", noPortalCustomer: "Dit account heeft nog geen beheerbaar facturatierecord."},
  pl: {manage: "Zarządzaj subskrypcją", busy: "Przetwarzanie...", checkoutError: "Płatność jest chwilowo niedostępna. Spróbuj ponownie później lub skontaktuj się z pomocą.", portalError: "Zarządzanie subskrypcją jest chwilowo niedostępne. Spróbuj ponownie później lub skontaktuj się z pomocą.", loginRequired: "Zaloguj się przed ulepszeniem planu.", addonUnavailable: "Pakiety dodatkowych minut są dostępne tylko dla kont z aktywną płatną subskrypcją.", noPortalCustomer: "To konto nie ma jeszcze możliwego do zarządzania rekordu rozliczeniowego."},
  pt: {manage: "Gerenciar assinatura", busy: "Processando...", checkoutError: "O pagamento está temporariamente indisponível. Tente novamente mais tarde ou fale com o suporte.", portalError: "O gerenciamento da assinatura está temporariamente indisponível. Tente novamente mais tarde ou fale com o suporte.", loginRequired: "Entre antes de atualizar seu plano.", addonUnavailable: "Pacotes de minutos adicionais estão disponíveis apenas para contas com assinatura paga ativa.", noPortalCustomer: "Esta conta ainda não tem um registro de cobrança gerenciável."},
  ru: {manage: "Управлять подпиской", busy: "Обработка...", checkoutError: "Оплата временно недоступна. Попробуйте позже или обратитесь в поддержку.", portalError: "Управление подпиской временно недоступно. Попробуйте позже или обратитесь в поддержку.", loginRequired: "Войдите в аккаунт перед обновлением тарифа.", addonUnavailable: "Дополнительные пакеты минут доступны только для аккаунтов с активной платной подпиской.", noPortalCustomer: "У этого аккаунта пока нет доступной для управления записи оплаты."},
  th: {manage: "จัดการการสมัครสมาชิก", busy: "กำลังประมวลผล...", checkoutError: "การชำระเงินไม่พร้อมใช้งานชั่วคราว โปรดลองอีกครั้งภายหลังหรือติดต่อฝ่ายสนับสนุน", portalError: "การจัดการการสมัครสมาชิกไม่พร้อมใช้งานชั่วคราว โปรดลองอีกครั้งภายหลังหรือติดต่อฝ่ายสนับสนุน", loginRequired: "โปรดเข้าสู่ระบบก่อนอัปเกรดแพ็กเกจ", addonUnavailable: "แพ็กเกจนาทีเสริมใช้ได้เฉพาะบัญชีที่มีการสมัครสมาชิกแบบชำระเงินที่ยังใช้งานอยู่", noPortalCustomer: "บัญชีนี้ยังไม่มีข้อมูลการเรียกเก็บเงินที่จัดการได้"},
  tr: {manage: "Aboneliği yönet", busy: "İşleniyor...", checkoutError: "Ödeme geçici olarak kullanılamıyor. Lütfen daha sonra tekrar deneyin veya destekle iletişime geçin.", portalError: "Abonelik yönetimi geçici olarak kullanılamıyor. Lütfen daha sonra tekrar deneyin veya destekle iletişime geçin.", loginRequired: "Planınızı yükseltmeden önce lütfen giriş yapın.", addonUnavailable: "Ek dakika paketleri yalnızca aktif ücretli aboneliği olan hesaplarda kullanılabilir.", noPortalCustomer: "Bu hesapta henüz yönetilebilir bir faturalandırma kaydı yok."},
  uk: {manage: "Керувати підпискою", busy: "Обробка...", checkoutError: "Оплата тимчасово недоступна. Спробуйте пізніше або зверніться до підтримки.", portalError: "Керування підпискою тимчасово недоступне. Спробуйте пізніше або зверніться до підтримки.", loginRequired: "Увійдіть перед оновленням плану.", addonUnavailable: "Додаткові пакети хвилин доступні лише для акаунтів з активною платною підпискою.", noPortalCustomer: "Цей акаунт ще не має керованого запису оплати."},
  vi: {manage: "Quản lý gói đăng ký", busy: "Đang xử lý...", checkoutError: "Thanh toán tạm thời không khả dụng. Vui lòng thử lại sau hoặc liên hệ hỗ trợ.", portalError: "Quản lý gói đăng ký tạm thời không khả dụng. Vui lòng thử lại sau hoặc liên hệ hỗ trợ.", loginRequired: "Vui lòng đăng nhập trước khi nâng cấp gói.", addonUnavailable: "Gói phút bổ sung chỉ khả dụng cho tài khoản có gói trả phí đang hoạt động.", noPortalCustomer: "Tài khoản này chưa có hồ sơ thanh toán có thể quản lý."},
  zh: {manage: "管理订阅", busy: "处理中...", checkoutError: "支付暂时不可用，请稍后重试或联系客服。", portalError: "订阅管理暂时不可用，请稍后重试或联系客服。", loginRequired: "请先登录后再升级套餐。", addonUnavailable: "加购分钟包仅适用于已订阅或 LTD 账户。", noPortalCustomer: "当前账号还没有可管理的账单记录。"},
  "zh-TW": {manage: "管理訂閱", busy: "處理中...", checkoutError: "付款暫時無法使用，請稍後再試或聯絡客服。", portalError: "訂閱管理暫時無法使用，請稍後再試或聯絡客服。", loginRequired: "請先登入後再升級方案。", addonUnavailable: "加購分鐘包僅適用於已訂閱或 LTD 帳戶。", noPortalCustomer: "目前帳號還沒有可管理的帳單記錄。"}
};

export function normalizeBillingLocale(value?: string | null): Locale {
  if (!value) return "en";
  const trimmed = value.trim();
  if (isLocale(trimmed)) return trimmed;
  const normalized = trimmed.toLowerCase();
  if (normalized === "zh-tw") return "zh-TW";
  return isLocale(normalized) ? normalized : "en";
}
