// SEO 着陆页白名单。`/[locale]/l/[slug]` 和语言页只允许这些 canonical slug，
// 既保留历史收录 URL，又避免把任意 slug 渲染成重复内容页面。
export const canonicalLandingSlugs = [
  "aac-to-srt",
  "aac-to-text",
  "academic-seminar-transcription",
  "ai-audio-transcription",
  "ai-legal-transcription",
  "ai-medical-transcription",
  "ai-meeting-summary",
  "amr-to-text",
  "audio-file-converter",
  "audio-to-pdf",
  "audio-to-srt",
  "audio-to-text-converter",
  "audio-to-txt",
  "audio-to-vtt",
  "audio-to-word",
  "best-transcription-software",
  "broadcast-media-transcription",
  "business-meeting-transcription",
  "classroom-recording-transcription",
  "convert-audio-recording",
  "flac-to-text",
  "google-speech-to-text",
  "lecture-transcription-app",
  "m4a-to-pdf",
  "m4a-to-srt",
  "m4a-to-text",
  "m4a-to-transcript",
  "m4a-to-txt",
  "m4a-to-vtt",
  "m4a-to-word",
  "mka-to-text",
  "mkv-to-text",
  "mov-to-pdf",
  "mov-to-srt",
  "mov-to-text",
  "mov-to-transcript",
  "mp3-to-pdf",
  "mp3-to-srt",
  "mp3-to-text",
  "mp3-to-txt",
  "mp3-to-vtt",
  "mp3-to-word",
  "mp4-to-pdf",
  "mp4-to-srt",
  "mp4-to-text-converter",
  "mp4-to-transcript",
  "mp4-to-txt",
  "mp4-to-vtt",
  "mp4-to-word",
  "mpeg-to-pdf",
  "mpeg-to-text",
  "mpeg-to-txt",
  "mpeg-to-word",
  "ogg-to-pdf",
  "ogg-to-text",
  "ogg-to-txt",
  "opus-to-pdf",
  "opus-to-text",
  "opus-to-txt",
  "podcast-to-text-converter",
  "record-lectures-transcription",
  "speech-to-text",
  "student-lecture-notes",
  "transcribe-mp4",
  "video-to-pdf",
  "video-to-srt",
  "video-to-text",
  "video-to-transcript",
  "video-to-txt",
  "video-to-vtt",
  "video-to-word",
  "voice-to-text",
  "wav-to-pdf",
  "wav-to-srt",
  "wav-to-text",
  "wav-to-transcript",
  "wav-to-txt",
  "wav-to-vtt",
  "wav-to-word",
  "webm-to-pdf",
  "webm-to-text",
  "webm-to-txt",
  "wma-to-text",
  "wmv-to-text",
  "youtube-to-srt",
  "youtube-to-text",
  "youtube-to-txt",
  "youtube-to-word",
  "youtube-transcript-generator"
] as const;

export const canonicalLanguageSlugs = [
  "transcribe-afrikaans-audio",
  "transcribe-albanian-audio",
  "transcribe-arabic-audio",
  "transcribe-azerbaijani-audio",
  "transcribe-basque-audio",
  "transcribe-belarusian-audio",
  "transcribe-bengali-audio",
  "transcribe-bosnian-audio",
  "transcribe-bulgarian-audio",
  "transcribe-cantonese-audio",
  "transcribe-catalan-audio",
  "transcribe-chinese-audio",
  "transcribe-croatian-audio",
  "transcribe-czech-audio",
  "transcribe-danish-audio",
  "transcribe-dutch-audio",
  "transcribe-english-audio",
  "transcribe-estonian-audio",
  "transcribe-finnish-audio",
  "transcribe-french-audio",
  "transcribe-galician-audio",
  "transcribe-german-audio",
  "transcribe-greek-audio",
  "transcribe-gujarati-audio",
  "transcribe-hebrew-audio",
  "transcribe-hindi-audio",
  "transcribe-hungarian-audio",
  "transcribe-indonesian-audio",
  "transcribe-italian-audio",
  "transcribe-japanese-audio",
  "transcribe-kannada-audio",
  "transcribe-kazakh-audio",
  "transcribe-korean-audio",
  "transcribe-latvian-audio",
  "transcribe-lithuanian-audio",
  "transcribe-macedonian-audio",
  "transcribe-malay-audio",
  "transcribe-malayalam-audio",
  "transcribe-marathi-audio",
  "transcribe-norwegian-audio",
  "transcribe-persian-audio",
  "transcribe-polish-audio",
  "transcribe-portuguese-audio",
  "transcribe-punjabi-audio",
  "transcribe-romanian-audio",
  "transcribe-russian-audio",
  "transcribe-serbian-audio",
  "transcribe-slovak-audio",
  "transcribe-slovenian-audio",
  "transcribe-spanish-audio",
  "transcribe-swahili-audio",
  "transcribe-swedish-audio",
  "transcribe-tagalog-audio",
  "transcribe-tamil-audio",
  "transcribe-telugu-audio",
  "transcribe-thai-audio",
  "transcribe-turkish-audio",
  "transcribe-ukrainian-audio",
  "transcribe-urdu-audio",
  "transcribe-vietnamese-audio",
  "transcribe-welsh-audio"
] as const;

const landingSlugSet = new Set<string>(canonicalLandingSlugs);
const languageSlugSet = new Set<string>(canonicalLanguageSlugs);

export function isCanonicalLandingSlug(slug: string) {
  // 用 Set 做运行时校验，避免路由层每次遍历长数组。
  return landingSlugSet.has(slug);
}

export function isCanonicalLanguageSlug(slug: string) {
  // 语言页也走白名单，避免不存在的语言 slug 被当成可索引页面。
  return languageSlugSet.has(slug);
}
