export const languageChoices = ["auto", "en", "zh", "es", "fr", "de", "ja", "ko", "pt"];
export const exportFormats = ["txt", "srt", "vtt", "json", "md", "csv", "docx", "pdf"];
export const outlineFormats = ["md", "txt", "json", "docx", "pdf"];

export const plans = [
  {key: "freePlan", price: "$0", minutes: "120", detail: "每日 3 个文件，单文件 30 分钟，适合轻量试用。"},
  {key: "basicPlan", price: "$6", minutes: "1200", detail: "支持 YouTube、发言人识别、批量任务和自动化导出。"},
  {key: "standardPlan", price: "$12", minutes: "3000", detail: "更高并发、更长文件和优先队列。"},
  {key: "proPlan", price: "$18", minutes: "6000", detail: "面向个人高频转写、课程整理和内容生产。"}
];

const faqs = [
  ["可以免费试用吗？", "可以。免费版包含月度分钟数、每日文件次数、转写编辑和标准导出能力。"],
  ["支持哪些文件？", "支持常见音频和视频格式，包括 mp3、wav、m4a、flac、mp4、mov、mkv、webm 和 wmv。"],
  ["如何生成发言人标签？", "开启后会优先使用 Deepgram 或 AssemblyAI 的说话人分离能力，失败时再 fallback 到 Groq 转写。"],
  ["可以导出字幕吗？", "可以。任务完成后可导出 SRT 和 VTT，也可以导出 TXT、JSON 和 PDF。"]
];

export const workspaceCopy = {
  zh: {
    intlLocale: "zh-CN",
    marketingIntro: "首屏即可上传、粘贴链接或录音，不需要先读完营销页。",
    freeSignup: "免费注册",
    viewDashboard: "查看仪表盘",
    converterTools: "转换工具",
    converters: ["语音转文字", "人声转文字", "音频转文字", "视频转文字", "链接转文字", "MP3 转文字", "MP4 转文字", "WAV 转文字"],
    freePlan: "免费计划",
    dailyFiles: "每日文件",
    monthlyMinutes: "每月分钟",
    queueTasks: "队列任务",
    account: "账号",
    anonymousUser: "未登录用户",
    loginSyncHint: "登录后同步任务和额度",
    retention: "保留期",
    days: "天",
    monthTasks: "本月任务",
    remainingMinutes: "剩余分钟",
    transcriptTab: "转写",
    translationTab: "翻译",
    noTranscriptAssets: "暂无转写资产。创建任务后会显示在这里。",
    noTranslationAssets: "暂无翻译资产。任务完成后点击生成 AI 洞察即可创建翻译。",
    targetLanguage: "目标语言",
    youtubeTask: "视频链接任务",
    unnamedTask: "未命名转写任务",
    waiting: "等待处理",
    speakers: (count: number) => `${count} 位发言人`,
    share: "分享",
    assetManagement: "资产管理",
    assetManagementText: "文件夹、搜索和批量操作用于管理会议、课程、采访和公开视频转写资产。",
    aiPost: "AI 后处理",
    aiPostText: "完成转写后继续生成摘要、思维导图、问答和翻译，减少手动整理成本。",
    exportText: "面向字幕、归档和自动化工作流，支持 TXT、SRT、VTT、JSON 和 PDF。",
    usageLedger: "用量流水",
    plan: "套餐",
    usedThisMonth: "本月已用",
    noLedger: "还没有用量流水。创建转写任务后会记录预留、结算和释放。",
    usageLoginEmpty: "登录并初始化订阅后会显示个人用量、账期和最近流水。",
    periodUnset: "未设置",
    whyTitle: "为什么选择 UniScribe",
    useCases: [
      ["学生和课程", "把讲座、网课、公开视频转成可检索笔记。"],
      ["个人会议", "保存会议录音、访谈、培训和语音备忘中的关键内容。"],
      ["创作者", "从视频生成字幕、脚本、博客草稿和社媒素材。"],
      ["研究和媒体", "快速处理采访、口述史、播客和新闻发布会。"]
    ],
    planDetails: {
      freePlan: "每日 3 个文件，单文件 30 分钟，适合轻量试用。",
      basicPlan: "支持 YouTube、发言人识别、批量任务和自动化导出。",
      standardPlan: "更高并发、更长文件和优先队列。",
      proPlan: "面向个人高频转写、课程整理和内容生产。"
    },
    minutesUnit: "分钟",
    viewFullPricing: "查看完整套餐",
    homeFaqs: faqs,
    needRecording: "请先完成一段录音。",
    needFile: "请先选择文件。",
    uploadUrlError: "无法创建上传地址。",
    uploadFailed: "文件上传失败，请检查对象存储配置。",
    createTaskError: "无法创建转写任务。",
    readTasksError: "无法读取转写任务列表。",
    readUsageError: "无法读取用量数据。",
    readTaskError: "无法读取转写任务。",
    shareTitle: "UniScribe 转写分享",
    shareError: "无法创建分享链接。",
    shareDone: "分享链接已创建并复制到剪贴板。",
    insightError: "无法生成 AI 洞察。",
    transcriptSaved: "转写文本已保存。",
    recordingReady: "录音已生成，可直接开始转写。",
    micError: "无法访问麦克风，请检查浏览器权限。",
    translationGenerated: "翻译内容已生成。"
  },
  en: {
    intlLocale: "en-US",
    marketingIntro: "Upload a file, paste a video link, or record audio and turn it into transcripts, summaries, and exports.",
    freeSignup: "Sign up free",
    viewDashboard: "View dashboard",
    converterTools: "Converters",
    converters: ["Speech to Text", "Voice to Text", "Audio to Text", "Video to Text", "Link to Text", "MP3 to Text", "MP4 to Text", "FLAC to Text", "AMR to Text", "WMA to Text", "MKV to Text", "WMV to Text"],
    freePlan: "Free plan",
    dailyFiles: "Daily files",
    monthlyMinutes: "Monthly minutes",
    queueTasks: "Queue tasks",
    account: "Account",
    anonymousUser: "Guest user",
    loginSyncHint: "Sign in to sync jobs and quota",
    retention: "Retention",
    days: "days",
    monthTasks: "Month tasks",
    remainingMinutes: "Remaining",
    transcriptTab: "Transcription",
    translationTab: "Translation",
    noTranscriptAssets: "No transcription assets yet. Create a job and it will appear here.",
    noTranslationAssets: "No translation assets yet. Generate AI insights after a completed job to create one.",
    targetLanguage: "Target",
    youtubeTask: "Video link task",
    unnamedTask: "Untitled transcription",
    waiting: "Waiting",
    speakers: (count: number) => `${count} speaker${count === 1 ? "" : "s"}`,
    share: "Share",
    assetManagement: "Asset management",
    assetManagementText: "Folders, search, and asset views help manage meetings, classes, interviews, and public-video transcripts.",
    aiPost: "AI post-processing",
    aiPostText: "After transcription, generate summaries, mind maps, Q&A, and translations to reduce manual cleanup.",
    exportText: "For captions, archives, and automation workflows, export TXT, SRT, VTT, JSON, and PDF.",
    usageLedger: "Usage ledger",
    plan: "Plan",
    usedThisMonth: "Used this month",
    noLedger: "No usage ledger yet. Creating transcription jobs will record reserve, settle, and release events.",
    usageLoginEmpty: "Sign in and initialize a subscription to see personal usage, billing period, and recent ledger entries.",
    periodUnset: "Not set",
    whyTitle: "Why UniScribe",
    useCases: [
      ["Students and courses", "Turn lectures, online classes, and public videos into searchable notes."],
      ["Personal meetings", "Preserve the key details from meetings, interviews, training, and voice memos."],
      ["Creators", "Create captions, scripts, blog drafts, and social content from video."],
      ["Research and media", "Process interviews, oral histories, podcasts, and press events faster."]
    ],
    planDetails: {
      freePlan: "3 files per day, 30 minutes per file, ideal for lightweight trials.",
      basicPlan: "YouTube links, speaker labels, batch tasks, and automation-ready exports.",
      standardPlan: "Higher concurrency, longer files, and priority queueing.",
      proPlan: "Built for high-volume personal transcription, courses, and content production."
    },
    minutesUnit: "min",
    viewFullPricing: "View full pricing",
    homeFaqs: [
      ["Can I try it for free?", "Yes. The Free plan includes monthly minutes, daily file limits, transcript editing, and standard exports."],
      ["Which files are supported?", "Common audio and video formats are supported, including mp3, wav, m4a, flac, mp4, mov, mkv, webm, and wmv."],
      ["How are speaker labels generated?", "When enabled, UniScribe prioritizes Deepgram or AssemblyAI diarization and falls back to Groq transcription if needed."],
      ["Can I export subtitles?", "Yes. Completed jobs can export SRT and VTT, plus TXT, JSON, and PDF."]
    ],
    needRecording: "Please finish a recording first.",
    needFile: "Please choose a file first.",
    uploadUrlError: "Unable to create upload URL.",
    uploadFailed: "File upload failed. Check object storage settings.",
    createTaskError: "Unable to create transcription task.",
    readTasksError: "Unable to read transcription tasks.",
    readUsageError: "Unable to read usage data.",
    readTaskError: "Unable to read transcription task.",
    shareTitle: "UniScribe transcript share",
    shareError: "Unable to create share link.",
    shareDone: "Share link created and copied to clipboard.",
    insightError: "Unable to generate AI insights.",
    transcriptSaved: "Transcript saved.",
    recordingReady: "Recording is ready. You can start transcription.",
    micError: "Unable to access microphone. Check browser permissions.",
    translationGenerated: "Translation has been generated."
  },
  es: {
    intlLocale: "es-ES",
    marketingIntro: "Sube, pega un enlace o graba de inmediato sin pasar primero por una página comercial.",
    freeSignup: "Regístrate gratis",
    viewDashboard: "Ver panel",
    converterTools: "Convertidores",
    converters: ["Voz a texto", "Audio a texto", "Video a texto", "Enlace a texto", "MP3 a texto", "MP4 a texto", "WAV a texto", "Subtítulos"],
    freePlan: "Plan gratis",
    dailyFiles: "Archivos diarios",
    monthlyMinutes: "Minutos mensuales",
    queueTasks: "Tareas en cola",
    account: "Cuenta",
    anonymousUser: "Usuario invitado",
    loginSyncHint: "Inicia sesión para sincronizar tareas y cuota",
    retention: "Retención",
    days: "días",
    monthTasks: "Tareas del mes",
    remainingMinutes: "Restante",
    transcriptTab: "Transcripción",
    translationTab: "Traducción",
    noTranscriptAssets: "Aún no hay transcripciones. Crea una tarea y aparecerá aquí.",
    noTranslationAssets: "Aún no hay traducciones. Genera insights de IA después de una tarea completada.",
    targetLanguage: "Destino",
    youtubeTask: "Tarea de enlace de video",
    unnamedTask: "Transcripción sin título",
    waiting: "En espera",
    speakers: (count: number) => `${count} hablante${count === 1 ? "" : "s"}`,
    share: "Compartir",
    assetManagement: "Gestión de activos",
    assetManagementText: "Carpetas, búsqueda y vistas de activos ayudan a gestionar reuniones, clases, entrevistas y transcripciones de videos públicos.",
    aiPost: "Postproceso con IA",
    aiPostText: "Después de transcribir, genera resúmenes, mapas mentales, preguntas y respuestas, y traducciones para reducir el trabajo manual.",
    exportText: "Para subtítulos, archivo y automatización, exporta TXT, SRT, VTT, JSON y PDF.",
    usageLedger: "Registro de uso",
    plan: "Plan",
    usedThisMonth: "Usado este mes",
    noLedger: "Aún no hay registro de uso. Las tareas de transcripción registrarán reservas, liquidaciones y liberaciones.",
    usageLoginEmpty: "Inicia sesión e inicializa una suscripción para ver tu uso, periodo de facturación y movimientos recientes.",
    periodUnset: "Sin definir",
    whyTitle: "Por qué UniScribe",
    useCases: [
      ["Estudiantes y cursos", "Convierte clases, cursos online y videos públicos en notas buscables."],
      ["Reuniones personales", "Conserva los puntos clave de Zoom, entrevistas, formaciones y reuniones con clientes."],
      ["Creadores", "Genera subtítulos, guiones, borradores de blog y contenido social desde video."],
      ["Investigación y medios", "Procesa entrevistas, historias orales, podcasts y ruedas de prensa más rápido."]
    ],
    planDetails: {
      freePlan: "3 archivos al día, 30 minutos por archivo, ideal para pruebas ligeras.",
      basicPlan: "Enlaces de YouTube, etiquetas de hablante, tareas por lote y exportaciones automatizadas.",
      standardPlan: "Más concurrencia, archivos más largos y cola prioritaria.",
      proPlan: "Para transcripción de alto volumen, reuniones frecuentes y flujos de producción de contenido."
    },
    minutesUnit: "min",
    viewFullPricing: "Ver precios completos",
    homeFaqs: [
      ["¿Puedo probarlo gratis?", "Sí. El plan gratuito incluye minutos mensuales, límites diarios, edición de transcripción y exportaciones estándar."],
      ["¿Qué archivos admite?", "Admite formatos comunes de audio y video, como mp3, wav, m4a, flac, mp4, mov, mkv, webm y wmv."],
      ["¿Cómo se generan las etiquetas de hablante?", "Al activarlas, UniScribe prioriza la diarización de Deepgram o AssemblyAI y recurre a Groq si hace falta."],
      ["¿Puedo exportar subtítulos?", "Sí. Las tareas completadas exportan SRT y VTT, además de TXT, JSON y PDF."]
    ],
    needRecording: "Primero termina una grabación.",
    needFile: "Primero elige un archivo.",
    uploadUrlError: "No se pudo crear la URL de carga.",
    uploadFailed: "Falló la carga del archivo. Revisa la configuración del almacenamiento.",
    createTaskError: "No se pudo crear la tarea de transcripción.",
    readTasksError: "No se pudieron leer las tareas de transcripción.",
    readUsageError: "No se pudieron leer los datos de uso.",
    readTaskError: "No se pudo leer la tarea de transcripción.",
    shareTitle: "Compartir transcripción de UniScribe",
    shareError: "No se pudo crear el enlace compartido.",
    shareDone: "Enlace compartido creado y copiado al portapapeles.",
    insightError: "No se pudieron generar insights de IA.",
    transcriptSaved: "Transcripción guardada.",
    recordingReady: "La grabación está lista. Puedes iniciar la transcripción.",
    micError: "No se pudo acceder al micrófono. Revisa los permisos del navegador.",
    translationGenerated: "La traducción se ha generado."
  },
  fr: {
    intlLocale: "fr-FR",
    marketingIntro: "Importez, collez un lien ou enregistrez immédiatement, sans lire d'abord une page marketing.",
    freeSignup: "Inscription gratuite",
    viewDashboard: "Voir le tableau",
    converterTools: "Convertisseurs",
    converters: ["Parole en texte", "Voix en texte", "Audio en texte", "Vidéo en texte", "Lien en texte", "MP3 en texte", "MP4 en texte", "WAV en texte"],
    freePlan: "Forfait gratuit",
    dailyFiles: "Fichiers par jour",
    monthlyMinutes: "Minutes mensuelles",
    queueTasks: "Tâches en file",
    account: "Compte",
    anonymousUser: "Utilisateur invité",
    loginSyncHint: "Connectez-vous pour synchroniser tâches et quota",
    retention: "Conservation",
    days: "jours",
    monthTasks: "Tâches du mois",
    remainingMinutes: "Restant",
    transcriptTab: "Transcription",
    translationTab: "Traduction",
    noTranscriptAssets: "Aucune transcription pour le moment. Créez une tâche et elle apparaîtra ici.",
    noTranslationAssets: "Aucune traduction pour le moment. Générez des analyses IA après une tâche terminée.",
    targetLanguage: "Cible",
    youtubeTask: "Tâche de lien vidéo",
    unnamedTask: "Transcription sans titre",
    waiting: "En attente",
    speakers: (count: number) => `${count} intervenant${count === 1 ? "" : "s"}`,
    share: "Partager",
    assetManagement: "Gestion des actifs",
    assetManagementText: "Dossiers, recherche et vues d'actifs aident à gérer réunions, cours, interviews et transcriptions de vidéos publiques.",
    aiPost: "Post-traitement IA",
    aiPostText: "Après transcription, générez résumés, cartes mentales, questions-réponses et traductions pour réduire le nettoyage manuel.",
    exportText: "Pour les sous-titres, archives et automatisations, exportez en TXT, SRT, VTT, JSON et PDF.",
    usageLedger: "Journal d'utilisation",
    plan: "Forfait",
    usedThisMonth: "Utilisé ce mois-ci",
    noLedger: "Aucun journal d'utilisation pour le moment. Les tâches de transcription enregistreront réservations, validations et libérations.",
    usageLoginEmpty: "Connectez-vous et initialisez un abonnement pour voir votre utilisation, la période de facturation et les mouvements récents.",
    periodUnset: "Non défini",
    whyTitle: "Pourquoi UniScribe",
    useCases: [
      ["Étudiants et cours", "Transformez conférences, cours en ligne et vidéos publiques en notes consultables."],
      ["Réunions personnelles", "Conservez les détails clés de Zoom, interviews, formations et réunions client."],
      ["Créateurs", "Créez sous-titres, scripts, brouillons de blog et contenus sociaux depuis une vidéo."],
      ["Recherche et médias", "Traitez plus vite interviews, récits oraux, podcasts et conférences de presse."]
    ],
    planDetails: {
      freePlan: "3 fichiers par jour, 30 minutes par fichier, idéal pour un essai léger.",
      basicPlan: "Liens YouTube, étiquettes d'intervenants, tâches par lot et exports automatisables.",
      standardPlan: "Plus de concurrence, fichiers plus longs et file prioritaire.",
      proPlan: "Conçu pour la transcription à haut volume, les réunions fréquentes et les chaînes de production de contenu."
    },
    minutesUnit: "min",
    viewFullPricing: "Voir tous les tarifs",
    homeFaqs: [
      ["Puis-je essayer gratuitement ?", "Oui. Le forfait gratuit inclut des minutes mensuelles, des limites quotidiennes, l'édition de transcription et les exports standard."],
      ["Quels fichiers sont pris en charge ?", "Les formats audio et vidéo courants sont pris en charge, dont mp3, wav, m4a, flac, mp4, mov, mkv, webm et wmv."],
      ["Comment les intervenants sont-ils identifiés ?", "Une fois activé, UniScribe privilégie Deepgram ou AssemblyAI pour la diarisation, puis bascule vers Groq si nécessaire."],
      ["Puis-je exporter des sous-titres ?", "Oui. Les tâches terminées exportent SRT et VTT, ainsi que TXT, JSON et PDF."]
    ],
    needRecording: "Terminez d'abord un enregistrement.",
    needFile: "Choisissez d'abord un fichier.",
    uploadUrlError: "Impossible de créer l'URL d'import.",
    uploadFailed: "Échec de l'import du fichier. Vérifiez le stockage objet.",
    createTaskError: "Impossible de créer la tâche de transcription.",
    readTasksError: "Impossible de lire les tâches de transcription.",
    readUsageError: "Impossible de lire les données d'utilisation.",
    readTaskError: "Impossible de lire la tâche de transcription.",
    shareTitle: "Partage de transcription UniScribe",
    shareError: "Impossible de créer le lien de partage.",
    shareDone: "Lien de partage créé et copié dans le presse-papiers.",
    insightError: "Impossible de générer les analyses IA.",
    transcriptSaved: "Transcription enregistrée.",
    recordingReady: "L'enregistrement est prêt. Vous pouvez lancer la transcription.",
    micError: "Impossible d'accéder au microphone. Vérifiez les autorisations du navigateur.",
    translationGenerated: "La traduction a été générée."
  },
  de: {
    intlLocale: "de-DE",
    marketingIntro: "Sofort hochladen, Link einfügen oder aufnehmen, ohne zuerst eine Marketingseite zu lesen.",
    freeSignup: "Kostenlos registrieren",
    viewDashboard: "Dashboard ansehen",
    converterTools: "Konverter",
    converters: ["Sprache zu Text", "Stimme zu Text", "Audio zu Text", "Video zu Text", "Link zu Text", "MP3 zu Text", "MP4 zu Text", "WAV zu Text"],
    freePlan: "Kostenloser Plan",
    dailyFiles: "Dateien pro Tag",
    monthlyMinutes: "Monatsminuten",
    queueTasks: "Warteschlange",
    account: "Konto",
    anonymousUser: "Gastnutzer",
    loginSyncHint: "Anmelden, um Aufgaben und Kontingent zu synchronisieren",
    retention: "Aufbewahrung",
    days: "Tage",
    monthTasks: "Monatsaufgaben",
    remainingMinutes: "Verbleibend",
    transcriptTab: "Transkription",
    translationTab: "Übersetzung",
    noTranscriptAssets: "Noch keine Transkriptionsdateien. Erstelle eine Aufgabe, dann erscheint sie hier.",
    noTranslationAssets: "Noch keine Übersetzungen. Erzeuge nach einer abgeschlossenen Aufgabe KI-Insights.",
    targetLanguage: "Ziel",
    youtubeTask: "Video-Link-Aufgabe",
    unnamedTask: "Unbenannte Transkription",
    waiting: "Wartet",
    speakers: (count: number) => `${count} Sprecher`,
    share: "Teilen",
    assetManagement: "Asset-Verwaltung",
    assetManagementText: "Ordner, Suche und Asset-Ansichten helfen bei Meetings, Kursen, Interviews und Transkripten öffentlicher Videos.",
    aiPost: "KI-Nachbearbeitung",
    aiPostText: "Erzeuge nach der Transkription Zusammenfassungen, Mindmaps, Q&A und Übersetzungen, um manuelle Arbeit zu reduzieren.",
    exportText: "Für Untertitel, Archive und Automatisierung exportierst du TXT, SRT, VTT, JSON und PDF.",
    usageLedger: "Nutzungsprotokoll",
    plan: "Plan",
    usedThisMonth: "Diesen Monat genutzt",
    noLedger: "Noch kein Nutzungsprotokoll. Transkriptionsaufgaben erfassen Reservierung, Abrechnung und Freigabe.",
    usageLoginEmpty: "Melde dich an und initialisiere ein Abo, um persönliche Nutzung, Abrechnungszeitraum und aktuelle Einträge zu sehen.",
    periodUnset: "Nicht gesetzt",
    whyTitle: "Warum UniScribe",
    useCases: [
      ["Studierende und Kurse", "Verwandle Vorlesungen, Onlinekurse und öffentliche Videos in durchsuchbare Notizen."],
      ["Persönliche Meetings", "Bewahre wichtige Details aus Zoom-Calls, Interviews, Trainings und Kundengesprächen."],
      ["Creator", "Erstelle Untertitel, Skripte, Blogentwürfe und Social Content aus Videos."],
      ["Recherche und Medien", "Verarbeite Interviews, Oral-History-Material, Podcasts und Presseevents schneller."]
    ],
    planDetails: {
      freePlan: "3 Dateien pro Tag, 30 Minuten pro Datei, ideal für leichte Tests.",
      basicPlan: "YouTube-Links, Sprecherlabels, Batch-Aufgaben und automatisierbare Exporte.",
      standardPlan: "Mehr Parallelität, längere Dateien und priorisierte Warteschlange.",
      proPlan: "Für häufige Meetings und Content-Produktionsabläufe."
    },
    minutesUnit: "Min.",
    viewFullPricing: "Alle Preise ansehen",
    homeFaqs: [
      ["Kann ich kostenlos testen?", "Ja. Der kostenlose Plan enthält Monatsminuten, Tageslimits, Transkriptbearbeitung und Standardexporte."],
      ["Welche Dateien werden unterstützt?", "Unterstützt werden gängige Audio- und Videoformate wie mp3, wav, m4a, flac, mp4, mov, mkv, webm und wmv."],
      ["Wie werden Sprecherlabels erzeugt?", "Wenn aktiviert, priorisiert UniScribe Deepgram oder AssemblyAI für Diarisierung und fällt bei Bedarf auf Groq zurück."],
      ["Kann ich Untertitel exportieren?", "Ja. Abgeschlossene Aufgaben können SRT und VTT sowie TXT, JSON und PDF exportieren."]
    ],
    needRecording: "Bitte beende zuerst eine Aufnahme.",
    needFile: "Bitte wähle zuerst eine Datei.",
    uploadUrlError: "Upload-URL konnte nicht erstellt werden.",
    uploadFailed: "Dateiupload fehlgeschlagen. Prüfe die Objektspeicher-Einstellungen.",
    createTaskError: "Transkriptionsaufgabe konnte nicht erstellt werden.",
    readTasksError: "Transkriptionsaufgaben konnten nicht gelesen werden.",
    readUsageError: "Nutzungsdaten konnten nicht gelesen werden.",
    readTaskError: "Transkriptionsaufgabe konnte nicht gelesen werden.",
    shareTitle: "UniScribe-Transkript teilen",
    shareError: "Teillink konnte nicht erstellt werden.",
    shareDone: "Teillink erstellt und in die Zwischenablage kopiert.",
    insightError: "KI-Insights konnten nicht erzeugt werden.",
    transcriptSaved: "Transkript gespeichert.",
    recordingReady: "Aufnahme ist bereit. Du kannst die Transkription starten.",
    micError: "Mikrofonzugriff nicht möglich. Prüfe die Browserberechtigungen.",
    translationGenerated: "Übersetzung wurde erzeugt."
  },
  ja: {
    intlLocale: "ja-JP",
    marketingIntro: "マーケティングページを読まなくても、すぐにアップロード、リンク貼り付け、録音を開始できます。",
    freeSignup: "無料登録",
    viewDashboard: "ダッシュボード",
    converterTools: "変換ツール",
    converters: ["音声をテキスト化", "声をテキスト化", "音声ファイルをテキスト化", "動画をテキスト化", "リンクをテキスト化", "MP3 をテキスト化", "MP4 をテキスト化", "WAV をテキスト化"],
    freePlan: "無料プラン",
    dailyFiles: "1日のファイル数",
    monthlyMinutes: "月間分数",
    queueTasks: "キュータスク",
    account: "アカウント",
    anonymousUser: "ゲストユーザー",
    loginSyncHint: "ログインしてタスクと利用枠を同期",
    retention: "保存期間",
    days: "日",
    monthTasks: "今月のタスク",
    remainingMinutes: "残り",
    transcriptTab: "文字起こし",
    translationTab: "翻訳",
    noTranscriptAssets: "文字起こし資産はまだありません。タスクを作成するとここに表示されます。",
    noTranslationAssets: "翻訳資産はまだありません。完了したタスクで AI インサイトを生成してください。",
    targetLanguage: "対象",
    youtubeTask: "動画リンクタスク",
    unnamedTask: "無題の文字起こし",
    waiting: "待機中",
    speakers: (count: number) => `${count} 名の話者`,
    share: "共有",
    assetManagement: "資産管理",
    assetManagementText: "フォルダ、検索、資産ビューで会議、授業、インタビュー、公開動画の文字起こしを管理できます。",
    aiPost: "AI 後処理",
    aiPostText: "文字起こし後に要約、マインドマップ、Q&A、翻訳を生成し、手作業の整理を減らします。",
    exportText: "字幕、保管、自動化ワークフロー向けに TXT、SRT、VTT、JSON、PDF を出力できます。",
    usageLedger: "利用履歴",
    plan: "プラン",
    usedThisMonth: "今月の使用量",
    noLedger: "利用履歴はまだありません。文字起こしタスク作成後に予約、確定、解放が記録されます。",
    usageLoginEmpty: "ログインしてサブスクリプションを初期化すると、個人利用状況、請求期間、最近の履歴が表示されます。",
    periodUnset: "未設定",
    whyTitle: "UniScribe が選ばれる理由",
    useCases: [
      ["学生と授業", "講義、オンライン授業、公開動画を検索可能なノートに変換します。"],
      ["個人の会議", "Zoom、インタビュー、研修、顧客会議の重要ポイントを保存します。"],
      ["クリエイター", "動画から字幕、台本、ブログ下書き、SNS 素材を作成します。"],
      ["調査とメディア", "インタビュー、オーラルヒストリー、ポッドキャスト、記者会見を素早く処理します。"]
    ],
    planDetails: {
      freePlan: "1日3ファイル、1ファイル30分まで。軽い試用に最適です。",
      basicPlan: "YouTube リンク、話者ラベル、バッチタスク、自動化向けエクスポートに対応。",
      standardPlan: "同時処理数、長時間ファイル、優先キューを強化。",
      proPlan: "高頻度の会議、コンテンツ制作パイプライン向け。"
    },
    minutesUnit: "分",
    viewFullPricing: "料金をすべて見る",
    homeFaqs: [
      ["無料で試せますか？", "はい。無料プランには月間分数、1日のファイル制限、文字起こし編集、標準エクスポートが含まれます。"],
      ["どのファイルに対応していますか？", "mp3、wav、m4a、flac、mp4、mov、mkv、webm、wmv など一般的な音声・動画形式に対応しています。"],
      ["話者ラベルはどう生成されますか？", "有効化すると Deepgram または AssemblyAI の話者分離を優先し、必要に応じて Groq にフォールバックします。"],
      ["字幕を出力できますか？", "はい。完了したタスクは SRT、VTT に加えて TXT、JSON、PDF を出力できます。"]
    ],
    needRecording: "先に録音を完了してください。",
    needFile: "先にファイルを選択してください。",
    uploadUrlError: "アップロード URL を作成できません。",
    uploadFailed: "ファイルのアップロードに失敗しました。オブジェクトストレージ設定を確認してください。",
    createTaskError: "文字起こしタスクを作成できません。",
    readTasksError: "文字起こしタスク一覧を取得できません。",
    readUsageError: "利用データを取得できません。",
    readTaskError: "文字起こしタスクを取得できません。",
    shareTitle: "UniScribe 文字起こし共有",
    shareError: "共有リンクを作成できません。",
    shareDone: "共有リンクを作成し、クリップボードへコピーしました。",
    insightError: "AI インサイトを生成できません。",
    transcriptSaved: "文字起こしを保存しました。",
    recordingReady: "録音の準備ができました。文字起こしを開始できます。",
    micError: "マイクにアクセスできません。ブラウザ権限を確認してください。",
    translationGenerated: "翻訳を生成しました。"
  },
  ko: {
    intlLocale: "ko-KR",
    marketingIntro: "마케팅 페이지를 읽지 않아도 바로 업로드, 링크 붙여넣기, 녹음을 시작할 수 있습니다.",
    freeSignup: "무료 가입",
    viewDashboard: "대시보드 보기",
    converterTools: "변환 도구",
    converters: ["음성을 텍스트로", "목소리를 텍스트로", "오디오를 텍스트로", "비디오를 텍스트로", "링크를 텍스트로", "MP3를 텍스트로", "MP4를 텍스트로", "WAV를 텍스트로"],
    freePlan: "무료 플랜",
    dailyFiles: "일일 파일",
    monthlyMinutes: "월간 분수",
    queueTasks: "대기 작업",
    account: "계정",
    anonymousUser: "게스트 사용자",
    loginSyncHint: "로그인하면 작업과 할당량이 동기화됩니다",
    retention: "보관 기간",
    days: "일",
    monthTasks: "이번 달 작업",
    remainingMinutes: "남은 시간",
    transcriptTab: "전사",
    translationTab: "번역",
    noTranscriptAssets: "아직 전사 자산이 없습니다. 작업을 만들면 여기에 표시됩니다.",
    noTranslationAssets: "아직 번역 자산이 없습니다. 완료된 작업에서 AI 인사이트를 생성하세요.",
    targetLanguage: "대상",
    youtubeTask: "동영상 링크 작업",
    unnamedTask: "제목 없는 전사",
    waiting: "대기 중",
    speakers: (count: number) => `${count}명 화자`,
    share: "공유",
    assetManagement: "자산 관리",
    assetManagementText: "폴더, 검색, 자산 보기로 회의, 수업, 인터뷰, 공개 동영상 전사를 관리합니다.",
    aiPost: "AI 후처리",
    aiPostText: "전사 후 요약, 마인드맵, Q&A, 번역을 생성해 수작업 정리를 줄입니다.",
    exportText: "자막, 보관, 자동화 워크플로를 위해 TXT, SRT, VTT, JSON, PDF로 내보냅니다.",
    usageLedger: "사용량 내역",
    plan: "플랜",
    usedThisMonth: "이번 달 사용량",
    noLedger: "아직 사용량 내역이 없습니다. 전사 작업 생성 후 예약, 정산, 해제가 기록됩니다.",
    usageLoginEmpty: "로그인하고 구독을 초기화하면 개인 사용량, 청구 기간, 최근 내역을 볼 수 있습니다.",
    periodUnset: "미설정",
    whyTitle: "UniScribe를 선택하는 이유",
    useCases: [
      ["학생과 강의", "강의, 온라인 수업, 공개 영상을 검색 가능한 노트로 바꿉니다."],
      ["개인 회의", "Zoom, 인터뷰, 교육, 고객 회의의 핵심 내용을 보존합니다."],
      ["크리에이터", "영상에서 자막, 스크립트, 블로그 초안, 소셜 콘텐츠를 만듭니다."],
      ["리서치와 미디어", "인터뷰, 구술 기록, 팟캐스트, 기자회견을 더 빠르게 처리합니다."]
    ],
    planDetails: {
      freePlan: "하루 3개 파일, 파일당 30분. 가벼운 체험에 적합합니다.",
      basicPlan: "YouTube 링크, 화자 라벨, 일괄 작업, 자동화용 내보내기를 지원합니다.",
      standardPlan: "더 높은 동시 처리, 더 긴 파일, 우선 대기열을 제공합니다.",
      proPlan: "잦은 회의, 콘텐츠 제작 파이프라인에 적합합니다."
    },
    minutesUnit: "분",
    viewFullPricing: "전체 요금 보기",
    homeFaqs: [
      ["무료로 체험할 수 있나요?", "네. 무료 플랜에는 월간 분수, 일일 파일 제한, 전사 편집, 표준 내보내기가 포함됩니다."],
      ["어떤 파일을 지원하나요?", "mp3, wav, m4a, flac, mp4, mov, mkv, webm, wmv 등 일반적인 오디오와 비디오 형식을 지원합니다."],
      ["화자 라벨은 어떻게 생성되나요?", "활성화하면 UniScribe는 Deepgram 또는 AssemblyAI의 화자 분리를 우선 사용하고 필요 시 Groq로 전환합니다."],
      ["자막을 내보낼 수 있나요?", "네. 완료된 작업은 SRT, VTT와 함께 TXT, JSON, PDF로 내보낼 수 있습니다."]
    ],
    needRecording: "먼저 녹음을 완료하세요.",
    needFile: "먼저 파일을 선택하세요.",
    uploadUrlError: "업로드 URL을 만들 수 없습니다.",
    uploadFailed: "파일 업로드에 실패했습니다. 객체 스토리지 설정을 확인하세요.",
    createTaskError: "전사 작업을 만들 수 없습니다.",
    readTasksError: "전사 작업 목록을 읽을 수 없습니다.",
    readUsageError: "사용량 데이터를 읽을 수 없습니다.",
    readTaskError: "전사 작업을 읽을 수 없습니다.",
    shareTitle: "UniScribe 전사 공유",
    shareError: "공유 링크를 만들 수 없습니다.",
    shareDone: "공유 링크가 생성되어 클립보드에 복사되었습니다.",
    insightError: "AI 인사이트를 생성할 수 없습니다.",
    transcriptSaved: "전사가 저장되었습니다.",
    recordingReady: "녹음이 준비되었습니다. 전사를 시작할 수 있습니다.",
    micError: "마이크에 접근할 수 없습니다. 브라우저 권한을 확인하세요.",
    translationGenerated: "번역이 생성되었습니다."
  },
  pt: {
    intlLocale: "pt-BR",
    marketingIntro: "Envie, cole um link ou grave imediatamente, sem passar primeiro por uma página de marketing.",
    freeSignup: "Cadastrar grátis",
    viewDashboard: "Ver painel",
    converterTools: "Conversores",
    converters: ["Fala para texto", "Voz para texto", "Áudio para texto", "Vídeo para texto", "Link para texto", "MP3 para texto", "MP4 para texto", "WAV para texto"],
    freePlan: "Plano grátis",
    dailyFiles: "Arquivos diários",
    monthlyMinutes: "Minutos mensais",
    queueTasks: "Tarefas na fila",
    account: "Conta",
    anonymousUser: "Usuário convidado",
    loginSyncHint: "Entre para sincronizar tarefas e cota",
    retention: "Retenção",
    days: "dias",
    monthTasks: "Tarefas do mês",
    remainingMinutes: "Restante",
    transcriptTab: "Transcrição",
    translationTab: "Tradução",
    noTranscriptAssets: "Ainda não há transcrições. Crie uma tarefa e ela aparecerá aqui.",
    noTranslationAssets: "Ainda não há traduções. Gere insights de IA após uma tarefa concluída.",
    targetLanguage: "Destino",
    youtubeTask: "Tarefa de link de vídeo",
    unnamedTask: "Transcrição sem título",
    waiting: "Aguardando",
    speakers: (count: number) => `${count} locutor${count === 1 ? "" : "es"}`,
    share: "Compartilhar",
    assetManagement: "Gestão de ativos",
    assetManagementText: "Pastas, busca e visualizações de ativos ajudam a gerenciar reuniões, aulas, entrevistas e transcrições de vídeos públicos.",
    aiPost: "Pós-processamento com IA",
    aiPostText: "Depois da transcrição, gere resumos, mapas mentais, perguntas e respostas, e traduções para reduzir a revisão manual.",
    exportText: "Para legendas, arquivos e automações, exporte TXT, SRT, VTT, JSON e PDF.",
    usageLedger: "Histórico de uso",
    plan: "Plano",
    usedThisMonth: "Usado este mês",
    noLedger: "Ainda não há histórico de uso. Tarefas de transcrição registrarão reserva, liquidação e liberação.",
    usageLoginEmpty: "Entre e inicialize uma assinatura para ver seu uso, período de cobrança e histórico recente.",
    periodUnset: "Não definido",
    whyTitle: "Por que UniScribe",
    useCases: [
      ["Estudantes e cursos", "Transforme palestras, aulas online e vídeos públicos em notas pesquisáveis."],
      ["Reuniões pessoais", "Preserve detalhes importantes de Zoom, entrevistas, treinamentos e reuniões com clientes."],
      ["Criadores", "Crie legendas, roteiros, rascunhos de blog e conteúdo social a partir de vídeo."],
      ["Pesquisa e mídia", "Processe entrevistas, histórias orais, podcasts e coletivas mais rápido."]
    ],
    planDetails: {
      freePlan: "3 arquivos por dia, 30 minutos por arquivo, ideal para testes leves.",
      basicPlan: "Links do YouTube, rótulos de locutor, tarefas em lote e exportações automatizáveis.",
      standardPlan: "Mais concorrência, arquivos mais longos e fila prioritária.",
      proPlan: "Para transcrição em alto volume, reuniões frequentes e pipelines de produção de conteúdo."
    },
    minutesUnit: "min",
    viewFullPricing: "Ver preços completos",
    homeFaqs: [
      ["Posso testar grátis?", "Sim. O plano grátis inclui minutos mensais, limites diários, edição de transcrição e exportações padrão."],
      ["Quais arquivos são suportados?", "Formatos comuns de áudio e vídeo são suportados, incluindo mp3, wav, m4a, flac, mp4, mov, mkv, webm e wmv."],
      ["Como os rótulos de locutor são gerados?", "Quando ativado, o UniScribe prioriza a diarização da Deepgram ou AssemblyAI e alterna para Groq se necessário."],
      ["Posso exportar legendas?", "Sim. Tarefas concluídas exportam SRT e VTT, além de TXT, JSON e PDF."]
    ],
    needRecording: "Conclua uma gravação primeiro.",
    needFile: "Escolha um arquivo primeiro.",
    uploadUrlError: "Não foi possível criar a URL de upload.",
    uploadFailed: "Falha no upload do arquivo. Verifique o armazenamento de objetos.",
    createTaskError: "Não foi possível criar a tarefa de transcrição.",
    readTasksError: "Não foi possível ler as tarefas de transcrição.",
    readUsageError: "Não foi possível ler os dados de uso.",
    readTaskError: "Não foi possível ler a tarefa de transcrição.",
    shareTitle: "Compartilhar transcrição UniScribe",
    shareError: "Não foi possível criar o link de compartilhamento.",
    shareDone: "Link de compartilhamento criado e copiado para a área de transferência.",
    insightError: "Não foi possível gerar insights de IA.",
    transcriptSaved: "Transcrição salva.",
    recordingReady: "A gravação está pronta. Você pode iniciar a transcrição.",
    micError: "Não foi possível acessar o microfone. Verifique as permissões do navegador.",
    translationGenerated: "A tradução foi gerada."
  }
} as const;

export type WorkspaceCopy = ReturnType<typeof getWorkspaceCopy>;

export function getWorkspaceCopy(locale: string) {
  const localeKey = locale.toLowerCase().split("-")[0] as keyof typeof workspaceCopy;
  const copy = workspaceCopy[localeKey] ?? workspaceCopy.en;
  return {
    ...copy,
    supportedPlatforms: ["YouTube", "TikTok", "Instagram", "Facebook", "X", "Many other links"]
  };
}

export const fallbackMessages: Record<string, string> = {
  uploadFile: "上传文件",
  pasteLink: "粘贴链接",
  recordAudio: "录音",
  headline: "音视频一键转文字",
  subheadline:
    "上传文件、粘贴视频链接或直接录音。UniScribe 会生成可编辑转写、发言人段落、AI 总结、思维导图、问答、翻译和多格式导出。",
  formats: "支持 11+ 媒体格式",
  languages: "支持 87 种语言",
  exportCount: "支持 5 种导出",
  allTranscriptions: "全部转写",
  uploadFiles: "上传文件",
  mediaLinkTranscription: "媒体链接转写",
  supportedPlatforms: "支持的平台",
  name: "名称",
  duration: "时长",
  created: "创建时间",
  type: "类型",
  folder: "文件夹",
  localUploadHint: "音频: aac, amr, awb, flac, m4a, mka, mp2, mp3, oga, ogg, opus, wav, weba, webm, wma。视频: 3gp, mkv, mov, mp4, mpg, ts, webm, wmv。",
  terms: "使用 UniScribe 即表示你同意服务条款和隐私政策。",
  ready: "就绪",
  save: "保存",
  workspace: "工作台",
  features: "功能",
  pricing: "价格",
  faq: "FAQ",
  blog: "博客",
  tryFree: "开始转写",
  workflowTitle: "从媒体到可用文本",
  workflowUpload: "上传、链接或录音",
  workflowUploadText: "本地文件直传对象存储，在线视频链接进入解析队列，浏览器录音会作为音频文件处理。",
  workflowTranscribe: "队列转写",
  workflowTranscribeText: "根据发言人标签、语言和服务可用性，在 Groq、Deepgram、AssemblyAI 之间自动切换。",
  workflowExport: "编辑与导出",
  workflowExportText: "完成后编辑全文，生成摘要、思维导图、问答、翻译，并下载字幕或文档。",
  insightTitle: "AI 工作区",
  summaryEmpty: "转写完成后可生成摘要和要点。",
  mindMapEmpty: "思维导图节点会显示在这里。",
  qaEmpty: "关键问答会显示在这里。",
  translationEmpty: "翻译会显示在这里。",
  plansTitle: "适合不同工作量的方案",
  freePlan: "免费版",
  basicPlan: "基础版",
  standardPlan: "标准版",
  proPlan: "专业版",
  perMonth: "/ 月",
  faqTitle: "常见问题",
  drop: "拖入音频或视频",
  choose: "或点击选择文件",
  youtube: "视频链接",
  youtubePlaceholder: "粘贴 YouTube、课程或公开视频链接",
  language: "转写语言",
  auto: "自动识别",
  speakerLabels: "发言人标签",
  start: "开始转写",
  status: "任务状态",
  transcript: "转写编辑器",
  summary: "摘要",
  mindMap: "思维导图",
  qa: "问答",
  translation: "翻译",
  exports: "导出中心",
  generateInsights: "生成 AI 洞察",
  empty: "选择一种输入方式开始。任务进度、转写文本和 AI 工作区会显示在这里。",
  processing: "处理中",
  completed: "已完成",
  failed: "失败",
  quotaTitle: "免费额度",
  quotaFiles: "今日文件",
  quotaMinutes: "本月分钟",
  taskList: "转写任务",
  searchPlaceholder: "搜索文件名",
  folders: "文件夹",
  uncategorized: "未分类",
  bulkActions: "批量操作",
  copied: "已复制到剪贴板",
  recordHint: "录音会在浏览器中生成 WebM 音频文件，然后走同一套上传和转写队列。",
  startRecord: "开始录音",
  stopRecord: "停止录音",
  noTranscript: "任务创建后，实时进度和转写结果会出现在这里。"
};
