import {isLocale, type Locale} from "@/lib/locales";

type YoutubeToolCopy = {
  placeholder: string;
  checkSubtitles: string;
  checkVideo: string;
  subtitleLanguageAria: string;
  subtitleFormatAria: string;
  automaticSuffix: string;
  download: string;
  captionsOnly: string;
  infoError: string;
  subtitlesError: string;
  noSubtitles: string;
  downloadError: string;
  prepareError: string;
  prepareDownload: string;
  transcribeInstead: string;
  readyTitle: string;
  readyText: string;
  openDownload: string;
  videosOnly: string;
};

const youtubeToolCopyByLocale: Record<Locale, YoutubeToolCopy> = {
  en: {
    placeholder: "Paste a YouTube video URL",
    checkSubtitles: "Check subtitles",
    checkVideo: "Check video",
    subtitleLanguageAria: "Subtitle language",
    subtitleFormatAria: "Subtitle format",
    automaticSuffix: "auto",
    download: "Download",
    captionsOnly: "Downloads public captions only",
    infoError: "Could not read video information.",
    subtitlesError: "Could not read subtitle list.",
    noSubtitles: "This video has no downloadable subtitles.",
    downloadError: "Could not download subtitles.",
    prepareError: "Could not prepare the video download URL.",
    prepareDownload: "Prepare download",
    transcribeInstead: "Transcribe instead",
    readyTitle: "Download link ready",
    readyText: "The link is generated from the public YouTube media source and can expire.",
    openDownload: "Open download",
    videosOnly: "Public videos only - respect creator rights and platform terms"
  },
  id: {
    placeholder: "Tempel URL video YouTube",
    checkSubtitles: "Periksa subtitle",
    checkVideo: "Periksa video",
    subtitleLanguageAria: "Bahasa subtitle",
    subtitleFormatAria: "Format subtitle",
    automaticSuffix: "otomatis",
    download: "Unduh",
    captionsOnly: "Hanya mengunduh subtitle publik",
    infoError: "Tidak dapat membaca informasi video.",
    subtitlesError: "Tidak dapat membaca daftar subtitle.",
    noSubtitles: "Video ini tidak memiliki subtitle yang dapat diunduh.",
    downloadError: "Tidak dapat mengunduh subtitle.",
    prepareError: "Tidak dapat menyiapkan URL unduhan video.",
    prepareDownload: "Siapkan unduhan",
    transcribeInstead: "Transkripsi saja",
    readyTitle: "Tautan unduhan siap",
    readyText: "Tautan dibuat dari sumber media YouTube publik dan dapat kedaluwarsa.",
    openDownload: "Buka unduhan",
    videosOnly: "Hanya video publik - hormati hak kreator dan ketentuan platform"
  },
  ru: {
    placeholder: "Вставьте URL видео YouTube",
    checkSubtitles: "Проверить субтитры",
    checkVideo: "Проверить видео",
    subtitleLanguageAria: "Язык субтитров",
    subtitleFormatAria: "Формат субтитров",
    automaticSuffix: "авто",
    download: "Скачать",
    captionsOnly: "Скачиваются только публичные субтитры",
    infoError: "Не удалось прочитать информацию о видео.",
    subtitlesError: "Не удалось прочитать список субтитров.",
    noSubtitles: "У этого видео нет доступных для скачивания субтитров.",
    downloadError: "Не удалось скачать субтитры.",
    prepareError: "Не удалось подготовить ссылку для скачивания видео.",
    prepareDownload: "Подготовить скачивание",
    transcribeInstead: "Транскрибировать",
    readyTitle: "Ссылка для скачивания готова",
    readyText: "Ссылка создана из публичного источника YouTube и может истечь.",
    openDownload: "Открыть скачивание",
    videosOnly: "Только публичные видео - уважайте права авторов и правила платформы"
  },
  es: {
    placeholder: "Pega una URL de video de YouTube",
    checkSubtitles: "Comprobar subtítulos",
    checkVideo: "Comprobar video",
    subtitleLanguageAria: "Idioma de subtítulos",
    subtitleFormatAria: "Formato de subtítulos",
    automaticSuffix: "auto",
    download: "Descargar",
    captionsOnly: "Solo descarga subtítulos públicos",
    infoError: "No se pudo leer la información del video.",
    subtitlesError: "No se pudo leer la lista de subtítulos.",
    noSubtitles: "Este video no tiene subtítulos descargables.",
    downloadError: "No se pudieron descargar los subtítulos.",
    prepareError: "No se pudo preparar la URL de descarga del video.",
    prepareDownload: "Preparar descarga",
    transcribeInstead: "Transcribir en su lugar",
    readyTitle: "Enlace de descarga listo",
    readyText: "El enlace se genera desde la fuente pública de YouTube y puede caducar.",
    openDownload: "Abrir descarga",
    videosOnly: "Solo videos públicos - respeta los derechos del creador y las normas de la plataforma"
  },
  vi: {
    placeholder: "Dán URL video YouTube",
    checkSubtitles: "Kiểm tra phụ đề",
    checkVideo: "Kiểm tra video",
    subtitleLanguageAria: "Ngôn ngữ phụ đề",
    subtitleFormatAria: "Định dạng phụ đề",
    automaticSuffix: "tự động",
    download: "Tải xuống",
    captionsOnly: "Chỉ tải phụ đề công khai",
    infoError: "Không thể đọc thông tin video.",
    subtitlesError: "Không thể đọc danh sách phụ đề.",
    noSubtitles: "Video này không có phụ đề có thể tải xuống.",
    downloadError: "Không thể tải phụ đề.",
    prepareError: "Không thể chuẩn bị URL tải video.",
    prepareDownload: "Chuẩn bị tải xuống",
    transcribeInstead: "Chuyển văn bản thay thế",
    readyTitle: "Liên kết tải xuống đã sẵn sàng",
    readyText: "Liên kết được tạo từ nguồn media YouTube công khai và có thể hết hạn.",
    openDownload: "Mở tải xuống",
    videosOnly: "Chỉ video công khai - tôn trọng quyền tác giả và điều khoản nền tảng"
  },
  ar: {
    placeholder: "الصق رابط فيديو YouTube",
    checkSubtitles: "فحص الترجمات",
    checkVideo: "فحص الفيديو",
    subtitleLanguageAria: "لغة الترجمة",
    subtitleFormatAria: "صيغة الترجمة",
    automaticSuffix: "تلقائي",
    download: "تنزيل",
    captionsOnly: "يتم تنزيل الترجمات العامة فقط",
    infoError: "تعذرت قراءة معلومات الفيديو.",
    subtitlesError: "تعذرت قراءة قائمة الترجمات.",
    noSubtitles: "لا يحتوي هذا الفيديو على ترجمات قابلة للتنزيل.",
    downloadError: "تعذر تنزيل الترجمات.",
    prepareError: "تعذر تجهيز رابط تنزيل الفيديو.",
    prepareDownload: "تجهيز التنزيل",
    transcribeInstead: "تفريغ بدلاً من ذلك",
    readyTitle: "رابط التنزيل جاهز",
    readyText: "تم إنشاء الرابط من مصدر YouTube عام وقد تنتهي صلاحيته.",
    openDownload: "فتح التنزيل",
    videosOnly: "الفيديوهات العامة فقط - احترم حقوق المبدعين وشروط المنصة"
  },
  pt: {
    placeholder: "Cole uma URL de vídeo do YouTube",
    checkSubtitles: "Verificar legendas",
    checkVideo: "Verificar vídeo",
    subtitleLanguageAria: "Idioma da legenda",
    subtitleFormatAria: "Formato da legenda",
    automaticSuffix: "auto",
    download: "Baixar",
    captionsOnly: "Baixa apenas legendas públicas",
    infoError: "Não foi possível ler as informações do vídeo.",
    subtitlesError: "Não foi possível ler a lista de legendas.",
    noSubtitles: "Este vídeo não tem legendas para baixar.",
    downloadError: "Não foi possível baixar as legendas.",
    prepareError: "Não foi possível preparar a URL de download do vídeo.",
    prepareDownload: "Preparar download",
    transcribeInstead: "Transcrever em vez disso",
    readyTitle: "Link de download pronto",
    readyText: "O link é gerado a partir da mídia pública do YouTube e pode expirar.",
    openDownload: "Abrir download",
    videosOnly: "Apenas vídeos públicos - respeite direitos do criador e termos da plataforma"
  },
  fr: {
    placeholder: "Collez une URL de vidéo YouTube",
    checkSubtitles: "Vérifier les sous-titres",
    checkVideo: "Vérifier la vidéo",
    subtitleLanguageAria: "Langue des sous-titres",
    subtitleFormatAria: "Format des sous-titres",
    automaticSuffix: "auto",
    download: "Télécharger",
    captionsOnly: "Télécharge uniquement les sous-titres publics",
    infoError: "Impossible de lire les informations de la vidéo.",
    subtitlesError: "Impossible de lire la liste des sous-titres.",
    noSubtitles: "Cette vidéo ne propose aucun sous-titre téléchargeable.",
    downloadError: "Impossible de télécharger les sous-titres.",
    prepareError: "Impossible de préparer l'URL de téléchargement de la vidéo.",
    prepareDownload: "Préparer le téléchargement",
    transcribeInstead: "Transcrire plutôt",
    readyTitle: "Lien de téléchargement prêt",
    readyText: "Le lien provient d'une source média YouTube publique et peut expirer.",
    openDownload: "Ouvrir le téléchargement",
    videosOnly: "Vidéos publiques uniquement - respectez les droits des créateurs et les conditions de la plateforme"
  },
  zh: {
    placeholder: "粘贴 YouTube 视频 URL",
    checkSubtitles: "检查字幕",
    checkVideo: "检查视频",
    subtitleLanguageAria: "字幕语言",
    subtitleFormatAria: "字幕格式",
    automaticSuffix: "自动",
    download: "下载",
    captionsOnly: "仅下载公开字幕",
    infoError: "无法读取视频信息。",
    subtitlesError: "无法读取字幕列表。",
    noSubtitles: "该视频没有可下载的字幕。",
    downloadError: "无法下载字幕。",
    prepareError: "无法准备视频下载地址。",
    prepareDownload: "准备下载",
    transcribeInstead: "改为转写",
    readyTitle: "下载链接已准备好",
    readyText: "链接来自公开 YouTube 媒体源，可能会过期。",
    openDownload: "打开下载",
    videosOnly: "仅支持公开视频 - 请尊重创作者权利和平台条款"
  },
  "zh-TW": {
    placeholder: "貼上 YouTube 影片 URL",
    checkSubtitles: "檢查字幕",
    checkVideo: "檢查影片",
    subtitleLanguageAria: "字幕語言",
    subtitleFormatAria: "字幕格式",
    automaticSuffix: "自動",
    download: "下載",
    captionsOnly: "僅下載公開字幕",
    infoError: "無法讀取影片資訊。",
    subtitlesError: "無法讀取字幕列表。",
    noSubtitles: "此影片沒有可下載的字幕。",
    downloadError: "無法下載字幕。",
    prepareError: "無法準備影片下載網址。",
    prepareDownload: "準備下載",
    transcribeInstead: "改為轉寫",
    readyTitle: "下載連結已準備好",
    readyText: "連結來自公開 YouTube 媒體來源，可能會過期。",
    openDownload: "開啟下載",
    videosOnly: "僅支援公開影片 - 請尊重創作者權利和平台條款"
  },
  de: {
    placeholder: "YouTube-Video-URL einfügen",
    checkSubtitles: "Untertitel prüfen",
    checkVideo: "Video prüfen",
    subtitleLanguageAria: "Untertitelsprache",
    subtitleFormatAria: "Untertitelformat",
    automaticSuffix: "auto",
    download: "Herunterladen",
    captionsOnly: "Lädt nur öffentliche Untertitel herunter",
    infoError: "Videoinformationen konnten nicht gelesen werden.",
    subtitlesError: "Untertitelliste konnte nicht gelesen werden.",
    noSubtitles: "Dieses Video hat keine herunterladbaren Untertitel.",
    downloadError: "Untertitel konnten nicht heruntergeladen werden.",
    prepareError: "Video-Download-URL konnte nicht vorbereitet werden.",
    prepareDownload: "Download vorbereiten",
    transcribeInstead: "Stattdessen transkribieren",
    readyTitle: "Download-Link bereit",
    readyText: "Der Link stammt aus einer öffentlichen YouTube-Medienquelle und kann ablaufen.",
    openDownload: "Download öffnen",
    videosOnly: "Nur öffentliche Videos - respektieren Sie Urheberrechte und Plattformbedingungen"
  },
  it: {
    placeholder: "Incolla un URL video di YouTube",
    checkSubtitles: "Controlla sottotitoli",
    checkVideo: "Controlla video",
    subtitleLanguageAria: "Lingua sottotitoli",
    subtitleFormatAria: "Formato sottotitoli",
    automaticSuffix: "auto",
    download: "Scarica",
    captionsOnly: "Scarica solo sottotitoli pubblici",
    infoError: "Impossibile leggere le informazioni del video.",
    subtitlesError: "Impossibile leggere l'elenco dei sottotitoli.",
    noSubtitles: "Questo video non ha sottotitoli scaricabili.",
    downloadError: "Impossibile scaricare i sottotitoli.",
    prepareError: "Impossibile preparare l'URL di download del video.",
    prepareDownload: "Prepara download",
    transcribeInstead: "Trascrivi invece",
    readyTitle: "Link di download pronto",
    readyText: "Il link viene generato da una fonte YouTube pubblica e può scadere.",
    openDownload: "Apri download",
    videosOnly: "Solo video pubblici - rispetta i diritti dei creator e i termini della piattaforma"
  },
  th: {
    placeholder: "วาง URL วิดีโอ YouTube",
    checkSubtitles: "ตรวจสอบคำบรรยาย",
    checkVideo: "ตรวจสอบวิดีโอ",
    subtitleLanguageAria: "ภาษาคำบรรยาย",
    subtitleFormatAria: "รูปแบบคำบรรยาย",
    automaticSuffix: "อัตโนมัติ",
    download: "ดาวน์โหลด",
    captionsOnly: "ดาวน์โหลดเฉพาะคำบรรยายสาธารณะ",
    infoError: "ไม่สามารถอ่านข้อมูลวิดีโอได้",
    subtitlesError: "ไม่สามารถอ่านรายการคำบรรยายได้",
    noSubtitles: "วิดีโอนี้ไม่มีคำบรรยายที่ดาวน์โหลดได้",
    downloadError: "ไม่สามารถดาวน์โหลดคำบรรยายได้",
    prepareError: "ไม่สามารถเตรียม URL ดาวน์โหลดวิดีโอได้",
    prepareDownload: "เตรียมดาวน์โหลด",
    transcribeInstead: "ถอดเสียงแทน",
    readyTitle: "ลิงก์ดาวน์โหลดพร้อมแล้ว",
    readyText: "ลิงก์สร้างจากแหล่งสื่อ YouTube สาธารณะและอาจหมดอายุ",
    openDownload: "เปิดดาวน์โหลด",
    videosOnly: "เฉพาะวิดีโอสาธารณะ - เคารพสิทธิ์ผู้สร้างและข้อกำหนดแพลตฟอร์ม"
  },
  uk: {
    placeholder: "Вставте URL відео YouTube",
    checkSubtitles: "Перевірити субтитри",
    checkVideo: "Перевірити відео",
    subtitleLanguageAria: "Мова субтитрів",
    subtitleFormatAria: "Формат субтитрів",
    automaticSuffix: "авто",
    download: "Завантажити",
    captionsOnly: "Завантажуються лише публічні субтитри",
    infoError: "Не вдалося прочитати інформацію про відео.",
    subtitlesError: "Не вдалося прочитати список субтитрів.",
    noSubtitles: "Це відео не має субтитрів для завантаження.",
    downloadError: "Не вдалося завантажити субтитри.",
    prepareError: "Не вдалося підготувати URL для завантаження відео.",
    prepareDownload: "Підготувати завантаження",
    transcribeInstead: "Транскрибувати",
    readyTitle: "Посилання для завантаження готове",
    readyText: "Посилання створено з публічного джерела YouTube і може застаріти.",
    openDownload: "Відкрити завантаження",
    videosOnly: "Лише публічні відео - поважайте права авторів і умови платформи"
  },
  tr: {
    placeholder: "YouTube video URL'si yapıştır",
    checkSubtitles: "Altyazıları kontrol et",
    checkVideo: "Videoyu kontrol et",
    subtitleLanguageAria: "Altyazı dili",
    subtitleFormatAria: "Altyazı biçimi",
    automaticSuffix: "otomatik",
    download: "İndir",
    captionsOnly: "Yalnızca herkese açık altyazıları indirir",
    infoError: "Video bilgisi okunamadı.",
    subtitlesError: "Altyazı listesi okunamadı.",
    noSubtitles: "Bu videoda indirilebilir altyazı yok.",
    downloadError: "Altyazılar indirilemedi.",
    prepareError: "Video indirme URL'si hazırlanamadı.",
    prepareDownload: "İndirmeyi hazırla",
    transcribeInstead: "Bunun yerine metne çevir",
    readyTitle: "İndirme bağlantısı hazır",
    readyText: "Bağlantı herkese açık YouTube medya kaynağından üretilir ve süresi dolabilir.",
    openDownload: "İndirmeyi aç",
    videosOnly: "Yalnızca herkese açık videolar - içerik üretici haklarına ve platform şartlarına uyun"
  },
  ja: {
    placeholder: "YouTube 動画 URL を貼り付け",
    checkSubtitles: "字幕を確認",
    checkVideo: "動画を確認",
    subtitleLanguageAria: "字幕言語",
    subtitleFormatAria: "字幕形式",
    automaticSuffix: "自動",
    download: "ダウンロード",
    captionsOnly: "公開字幕のみダウンロードします",
    infoError: "動画情報を読み取れませんでした。",
    subtitlesError: "字幕リストを読み取れませんでした。",
    noSubtitles: "この動画にはダウンロード可能な字幕がありません。",
    downloadError: "字幕をダウンロードできませんでした。",
    prepareError: "動画ダウンロード URL を準備できませんでした。",
    prepareDownload: "ダウンロードを準備",
    transcribeInstead: "代わりに文字起こし",
    readyTitle: "ダウンロードリンクの準備完了",
    readyText: "リンクは公開 YouTube メディアソースから生成され、有効期限があります。",
    openDownload: "ダウンロードを開く",
    videosOnly: "公開動画のみ - クリエイターの権利とプラットフォーム規約を尊重してください"
  },
  nl: {
    placeholder: "Plak een YouTube-video-URL",
    checkSubtitles: "Ondertitels controleren",
    checkVideo: "Video controleren",
    subtitleLanguageAria: "Ondertiteltaal",
    subtitleFormatAria: "Ondertitelformaat",
    automaticSuffix: "auto",
    download: "Downloaden",
    captionsOnly: "Downloadt alleen openbare ondertitels",
    infoError: "Kan video-informatie niet lezen.",
    subtitlesError: "Kan ondertitellijst niet lezen.",
    noSubtitles: "Deze video heeft geen downloadbare ondertitels.",
    downloadError: "Kan ondertitels niet downloaden.",
    prepareError: "Kan video-download-URL niet voorbereiden.",
    prepareDownload: "Download voorbereiden",
    transcribeInstead: "In plaats daarvan transcriberen",
    readyTitle: "Downloadlink klaar",
    readyText: "De link is gemaakt vanuit een openbare YouTube-mediabron en kan verlopen.",
    openDownload: "Download openen",
    videosOnly: "Alleen openbare video's - respecteer makersrechten en platformvoorwaarden"
  },
  pl: {
    placeholder: "Wklej URL filmu YouTube",
    checkSubtitles: "Sprawdź napisy",
    checkVideo: "Sprawdź wideo",
    subtitleLanguageAria: "Język napisów",
    subtitleFormatAria: "Format napisów",
    automaticSuffix: "auto",
    download: "Pobierz",
    captionsOnly: "Pobiera tylko publiczne napisy",
    infoError: "Nie udało się odczytać informacji o filmie.",
    subtitlesError: "Nie udało się odczytać listy napisów.",
    noSubtitles: "Ten film nie ma napisów do pobrania.",
    downloadError: "Nie udało się pobrać napisów.",
    prepareError: "Nie udało się przygotować adresu pobierania wideo.",
    prepareDownload: "Przygotuj pobieranie",
    transcribeInstead: "Zamiast tego transkrybuj",
    readyTitle: "Link do pobrania gotowy",
    readyText: "Link pochodzi z publicznego źródła YouTube i może wygasnąć.",
    openDownload: "Otwórz pobieranie",
    videosOnly: "Tylko publiczne filmy - szanuj prawa twórców i regulamin platformy"
  },
  ko: {
    placeholder: "YouTube 비디오 URL 붙여넣기",
    checkSubtitles: "자막 확인",
    checkVideo: "비디오 확인",
    subtitleLanguageAria: "자막 언어",
    subtitleFormatAria: "자막 형식",
    automaticSuffix: "자동",
    download: "다운로드",
    captionsOnly: "공개 자막만 다운로드합니다",
    infoError: "비디오 정보를 읽을 수 없습니다.",
    subtitlesError: "자막 목록을 읽을 수 없습니다.",
    noSubtitles: "이 비디오에는 다운로드 가능한 자막이 없습니다.",
    downloadError: "자막을 다운로드할 수 없습니다.",
    prepareError: "비디오 다운로드 URL을 준비할 수 없습니다.",
    prepareDownload: "다운로드 준비",
    transcribeInstead: "대신 전사",
    readyTitle: "다운로드 링크 준비 완료",
    readyText: "링크는 공개 YouTube 미디어 소스에서 생성되며 만료될 수 있습니다.",
    openDownload: "다운로드 열기",
    videosOnly: "공개 비디오만 지원 - 창작자 권리와 플랫폼 약관을 존중하세요"
  },
  hu: {
    placeholder: "YouTube videó URL beillesztése",
    checkSubtitles: "Feliratok ellenőrzése",
    checkVideo: "Videó ellenőrzése",
    subtitleLanguageAria: "Felirat nyelve",
    subtitleFormatAria: "Felirat formátuma",
    automaticSuffix: "automatikus",
    download: "Letöltés",
    captionsOnly: "Csak nyilvános feliratokat tölt le",
    infoError: "Nem sikerült beolvasni a videó adatait.",
    subtitlesError: "Nem sikerült beolvasni a feliratlistát.",
    noSubtitles: "Ehhez a videóhoz nincs letölthető felirat.",
    downloadError: "Nem sikerült letölteni a feliratokat.",
    prepareError: "Nem sikerült előkészíteni a videó letöltési URL-jét.",
    prepareDownload: "Letöltés előkészítése",
    transcribeInstead: "Inkább átírás",
    readyTitle: "Letöltési link kész",
    readyText: "A link nyilvános YouTube médiaforrásból készül, és lejárhat.",
    openDownload: "Letöltés megnyitása",
    videosOnly: "Csak nyilvános videók - tartsa tiszteletben az alkotói jogokat és a platform feltételeit"
  }
};

export function getYoutubeToolCopy(locale: string): YoutubeToolCopy {
  return youtubeToolCopyByLocale[isLocale(locale) ? locale : "en"];
}
